### ISSUE TITLE
1's everywhere are cumbersome

### ISSUE THREAD

**Issue by martijnhoekstra** [typelevel/cats-parse#113]
This issue may be a bit premature/pretentious to file as an issue, but I figured it would be good to get it out early. The safety that `Parser1` and its combinators are great. So great, that while trying out the library, I find I use them pretty much all the time. Using a `Parser` or a method that creates a `Parser` is an exception.

Has it been considered doing the other way around, renaming `Parser` to `Parser0`, and `Parser1` to `Parser`, along with all `1` methods on object `Parser`? That would make the potentially non-consuming Parsers the exception not only in practice but also in naming.

**Comment by johnynek** [comment]
This is a very interesting suggestion. Honestly, the Parser1 idea came after the library had somewhat been implemented, and I didn't reconsider your idea.

I agree that generally I use Parser1, basically only Parser (Parser0) for whitespace or parsing the inside of repeated structures (the result of rep).

Would you be willing to make a PR to explore this change?

**Comment by martijnhoekstra** [comment]
Sure, I'll see if I can get that done this weekend.

**Comment by johnynek** [comment]
@rossabaker you might also have an opinion here.

My bias in general is to live with warts and don't break users. That said, we may have very few users at this point and they may appreciate the change anyway.

There are also two questions:

1. Do we just rename the types
2. Do we also rename the methods so that we remove trailing 1 and instead use trailing 0 for parsers that can be empty.

**Comment by johnynek** [comment]
@regadas id love for you to weigh in too. You've been quite active here.

**Comment by rossabaker** [comment]
As one of the few users, it's version 0.2, the project was announced like a month ago, and I'd rather change a few things now and get it right than live with it wrong forever.  And Somebody™ could always write a scalafix.

> Do we also rename the methods so that we remove trailing 1 and instead use trailing 0 for parsers that can be empty.

I think it would be confusing if we didn't.

**Comment by martijnhoekstra** [comment]
Sloppy WIP at https://github.com/typelevel/cats-parse/compare/main...martijnhoekstra:Parser0?expand=1

Preliminary looks of things

* Combinators look much nicer without the 1 everywhere
* Do the right thing by default
* Constructors on object `Parser0` look bad. They should probably be moved to a to be newly introduced `object Parser`. Note that you can't straight up rename it, because Impl is private and parseMut is protected

**Comment by johnynek** [comment]
Could we introduce an object Parser0 and move all the Impl object there. Then in object Parser we put all the constructors that make Parser and put all the ones that make Parser0 on the object Parser0?

**Comment by martijnhoekstra** [comment]
I think so. It's the first direction I want to explore when the baseline is done.

**Comment by regadas** [comment]
Maybe I'm an odd duck but I actually fancy the `Parser` and `Parser1` naming. I'm not yet sure which ones get more use over the other as I think it will depend on your use case? Looking at http4s PR's things look "nice" to me.

I do reckon that some of the methods i.e. `Parser1#orElse1` can see the `1` being dropped.

I'm still a bit unsure and I'll give it more thought. 

Thanks!

**Comment by johnynek** [comment]
Thanks for #116 ! I'll look in detail today.

One argument against the change: Parser1 is the unusual thing: the pretty much all parser combinator libraries assume Parser can be an Applicative or Monad, which requires them to be able to parse 0 from the inputs.

**Comment by martijnhoekstra** [comment]
Under this scheme, Parser is an example of a data type with FlatMap instance, but no pure. Coming full circle: https://github.com/typelevel/cats/issues/3 I'm not sure if that can be provided in some way without clashing implicits. Maybe it can?

The instances on Parser0 are still valid, of course.

**Comment by johnynek** [comment]
:) indeed, this is probably the most compelling instance I've seen. Others have been Map and Tuples (which are kind of like maps with 1 key).

**Comment by ritschwumm** [comment]
i like the change a lot - if you ask me, the new Numbers parser alone in martijn's PR is pretty convincing already.
