### ISSUE TITLE
Is it possible to implement a non-greedy repeat?

### ISSUE THREAD

**Issue by FloWi** [typelevel/cats-parse#129]
I'm trying to implement a parser that repeats parser p1 until the rest of the string matches parser p2.
My current solution is this, but it's not really elegant and needs the input string to work. 

```scala
  def repeatUntil2ndParserMatches(input: String, p1: P[String], p2: P[String], maxRepetitions: Int = 100): P[String] = {
    import cats.syntax.applicative._
    LazyList
      .range(1, maxRepetitions)
      .flatMap { i =>
        println(s"trying p1 $i times")
        val newP1 = p1.backtrack.replicateA(i)
        val p1Result = newP1.parse(input)
        p1Result match {
          case Left(_) =>
            List(P.fail)

          case Right((rest, _)) =>
            val p2Result = p2.backtrack.parse(rest)
            p2Result match {
              case Left(_) => List.empty
              case Right(_) =>
                List((newP1 ~ p2).map { case (list, res2) => list.appended(res2) }.map(_.mkString))
            }
        }
      }
      .headOption match {
        case Some(value) => value
        case None        => P.fail
    }
  }
```
Can this be done more elegantly? 
I don't know if that is a common use-case in the parser world, but do know that regex groups can be made non-greedy.
I saw #128 where repetition is being discussed - maybe that is something others might find useful.

Maybe it'd be helpful if there was a combinator similar to flatMap that provides the tuple of `(remainder, matched)`.

**Comment by martijnhoekstra** [comment]
Maybe

```
def eitherOr0[A, B](first: Parser[B], second: Parser[A]): Parser[Either[A, B]] =
    Parser.oneOf(first.map(Right(_)) :: second.map(Left(_)) :: Nil)

def repeatUntil[A, B](r: Parser1[A], until: Parser[B]): Parser[(List[A], B)] = {
  val recurse = Parser.defer(repeatUntil(r, until))
  eitherOr0(until, r).flatMap {
    case Left(a) => recurse.map { case (as, b) => (as :+ a) -> b}
    case Right(b) => Parser.pure(Nil -> b)
  }
}
```

**Comment by johnynek** [comment]
I think @martijnhoekstra 's suggestion works. The only change I would make is to use `cats.data.Chain` to append on the right. List costs O(N) to do that, so this whole algorithm would be O(N^2). That or use Vector, which can append to the end somewhat efficiently, but not as cheaply as Chain.

**Comment by johnynek** [comment]
Also, if possible, I would make `until` a Parser1.

**Comment by johnynek** [comment]
One more... you can implement this with select rather than having to use flatMap, which may be a bit more efficient.

**Comment by FloWi** [comment]
Thanks a lot for your help, @martijnhoekstra! Works like a charm!
@johnynek, I'll try to improve his solution with your suggestions. Thanks for your quick help!

**Comment by FloWi** [comment]
Here the impl. with the suggested changes. It's a very cool library, once you get the hang of it :) Thanks for your work on it!
```scala
  import cats.parse.Parser
  import cats.data.Chain

  def eitherOr0[A, B](first: Parser1[B], second: Parser[A]): Parser[Either[A, B]] =
    Parser.oneOf(first.map(Right(_)) :: second.map(Left(_)) :: Nil)

  def repeatUntil[A, B](r: Parser[A], until: Parser1[B]): Parser[(Chain[A], B)] = {

    val recurse = Parser.defer(repeatUntil(r, until))
    eitherOr0(until, r).flatMap {
      case Left(a)  => recurse.map { case (as, b) => (as :+ a) -> b }
      case Right(b) => P.pure(Chain.empty[A] -> b)
    }
  }
```

**Comment by carueda** [comment]
Thanks @FloWi and all, for this entry and the solution. I just thought I'd add here that I made it work for a parser I'm writing, with the following: 

```scala
import cats.parse.{Parser0 => P0, Parser => P}
import cats.data.Chain

def eitherOr0[A, B](first: P[B], second: P[A]): P[Either[A, B]] =
  first.backtrack.map(Right(_)) | second.map(Left(_))

def repeatUntil[A, B](r: P[A], until: P[B]): P[(Chain[A], B)] =
  P.recursive[(Chain[A], B)] { recurse =>
    eitherOr0(until, r) flatMap {
      case Left(a)  => recurse.map { case (as, b) => (as :+ a) -> b }
      case Right(b) => P.pure(Chain.empty[A] -> b)
    }
  }
```

That is, the key change that made it work for me was the use `a.backtrack | b` instead of `P.oneOf` in `eitherOr0`.  I'm not (yet ;) an expert on cats-parse but I fully agree, it's a very cool library!
