### ISSUE TITLE
something broken in the build

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats-parse#154]
both #152 and #153 have failed with the same error.

It looks like something transitively is breaking the use of the name `params` in the build.sbt.

**Comment by johnynek** [comment]
https://github.com/typelevel/cats-parse/blob/dd067057b664ae317ecc6f456d8979c5e63cc10e/build.sbt#L68

that line works in main, but if we update we get an error.

Any ideas @mpilquist or @djspiewak ?

**Comment by djspiewak** [comment]
Oh I think I forgot to add something to release notes. WorkflowStep.Use now takes a UseRef, which allows for steps that run in containers. So it's the first three parameters that are wrong here

**Comment by johnynek** [comment]
all of a sudden, everything is broken, here is a different exiting build error: #155
