### ISSUE TITLE
Add a way to modify error messages

### ISSUE THREAD

**Issue by morgen-peschke** [typelevel/cats-parse#183]
Some of the error messages produce results that are either hard to render, or not particularly clear. This could be improved by providing the ability to replace or map over the error. 

For example, if we have this parser(which is equivalent to `-\s-`):
```scala
import cats.parse.{Parser => P}
val parser = P.charWhere(_.isWhitespace).surroundedBy(P.char('-'))

List(
  "- -",
  "-t-",
  "--"
).foreach { input =>
  println("%-10s \t => %s".format(s""""$input"""", parser.parseAll(input)))
}
```

We get errors that aren't terribly readable:
```
"- -"      	 => Right( )
"-t-"      	 => Left(Error(1,NonEmptyList(InRange(1,	,
), InRange(1,, ), InRange(1, , ), InRange(1,᠎,᠎), InRange(1, , ), InRange(1, , ), InRange(1, , ), InRange(1, , ), InRange(1,　,　))))
"--"       	 => Left(Error(1,NonEmptyList(InRange(1,	,
), InRange(1,, ), InRange(1, , ), InRange(1,᠎,᠎), InRange(1, , ), InRange(1, , ), InRange(1, , ), InRange(1, , ), InRange(1,　,　))))
```

It would be handy to do something like fastparse's `opaque`:
```scala
parser.opaque("whitespace")
```
Or a lower level map over the errors:
```scala
parser.leftMap { error =>
  case InRange(index, _) => FailWith(index, "whitespace")
  case unexpected => unexpected
}
```

Which could produce errors like this:
```
"- -"      	 => Left(Error(1,NonEmptyList(FailWith(1,whitespace))))
"-t-"      	 => Left(Error(1,NonEmptyList(FailWith(1,whitespace))))
"--"       	 => Left(Error(1,NonEmptyList(FailWith(1,whitespace))))
```

**Comment by johnynek** [comment]
I think this is quite related to #43 

What do you think of the solution proposed there? One thing I like about avoiding opaque is that we can generally report what was expected, so you can make clearer suggestions to users (just printing the error won't work well, but you can render them nicely and in context in principle, https://github.com/johnynek/bosatsu does this, but it uses typelevel/paiges to do it, and I have been reluctant to add the dependency in this project).

**Comment by morgen-peschke** [comment]
That would definitely improve the situation. 

If I'm understanding #43 correctly, it would allow customizing the rendering of the error based on the scope, allowing the reporter to render the whitespace in the errors above as something like `"\t\n\u000b\f\r\u001c\u001d\u001e\u001f  ᠎\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2008\u2009\u200a\u2028\u2029\u205f　"`, which would be much easier to differentiate between the available options.

Attaching an offset to a scope could help clarify one part of the error encoding that's currently a bit unclear: what is the difference between the offset in the parent `Error` and the offsets contained in each `Expectation`?
