### ISSUE TITLE
Parser0[Option[_]] ~ Parser[_] could not get (Option(_), _)

### ISSUE THREAD

**Issue by timzaak** [typelevel/cats-parse#186]
```scala
  import cats.parse.{Parser0, Parser => P, Numbers}
  private def name:P[String] = P.charIn(('a' to 'z')).rep.string
  private def alias: P[String] = name <* P.char(':')
  (alias.? ~ name).parse("abc")

```
the code will return `Left(Error(3,NonEmptyList(InRange(3,:,:))))` , It should be `Right(_, (None,abc))`.
I tried `(alias.?.backtrack ~ name)` , `(alias.?.soft ~ name)`, both does not work.

**Comment by timzaak** [comment]
```
private def alias: P[String] = name.soft <* P.char(':')
```  
works

**Comment by timzaak** [comment]
need more example about soft and backtrack

**Comment by johnynek** [comment]
I think you had the order wrong: `.backtrack.?` would have worked, although `name.soft <* P.char(':')` is more precise.

**Comment by timzaak** [comment]
@johnynek  thanks, it works.
