### ISSUE TITLE
Problem with Maven RC2 release?

### ISSUE THREAD

**Issue by bblfish** [typelevel/cats-parse#197]
I got the following message trying to open Rfc5234 in IntelliJ

```
Error reading TASTy file: /Users/hjs/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/typelevel/cats-parse_3.0.0-RC2/0.3-3-d801d0a/cats-parse_3.0.0-RC2-0.3-3-d801d0a.jar!/cats/parse/Rfc5234.tasty
```

I tried other versions of [cats-parse for RC2 from maven central](https://search.maven.org/artifact/org.typelevel/cats-parse_3.0.0-RC2) with the same result. 

As this is a bit bleeding edge it could be IntelliJ or the deployed library. Just thought I'd ping you here.

**Comment by johnynek** [comment]
Huh, I don't know any problem. Did you check if you could resolve the actual jar?

**Comment by bblfish** [comment]
I have moved to scala3 RC3 now, so it would be a bit difficult to test now. Can you ping this issue when the RC3 release is out, I can try then?

Otherwise I was very successful writing an [RFC8941](https://github.com/co-operating-systems/Reactive-SoLiD/issues/13) parser with Cats-Parse.
