### ISSUE TITLE
CPU time spent in hashcode computation

### ISSUE THREAD

**Issue by ghostdogpr** [typelevel/cats-parse#198]
Hi,
We are currently trying to replace fastparse by cats-parse and ran into the issue that parsing became 3 to 30x slower than it was with fastparse. Using a profiler, I saw that most of the CPU is actually spent on calculating hashcode, triggered by the use of `.distinct` in `oneOf`. See the following screenshots:

<img width="1303" alt="Screen Shot 2021-04-10 at 3 07 25 PM" src="https://user-images.githubusercontent.com/7413894/114260265-b6addf80-9a0e-11eb-8ae7-6a14e30b3b10.png">
<img width="1350" alt="Screen Shot 2021-04-10 at 3 09 53 PM" src="https://user-images.githubusercontent.com/7413894/114260284-cfb69080-9a0e-11eb-907b-0d5494e455dd.png">

Do you think this is caused by a wrong use of cat-parse, or is it something that can improved in cats-parse itself? Parser code can be found [here](https://github.com/ghostdogpr/caliban/pull/834/files#diff-03436de4a1f55d01b6f3ca37b998f2c4293c8b0249fa1d1fc9c6afbe22538dfb) if it helps.

**Comment by ritschwumm** [comment]
without knowing anything about the details - it might make sense to cache the hashCode of Parser with something like the code below. i'm not sure this is valid here, but it's quite often the easiest way to improve the performance of map lookups:
```override val hashCode:Int	= scala.runtime.ScalaRunTime._hashCode(this)```

**Comment by johnynek** [comment]
Yeah, caching the hashCode seems like a good idea since we use distinct. If you have time for a PR that would be great.

**Comment by ghostdogpr** [comment]
Sure, I opened https://github.com/typelevel/cats-parse/pull/200.

With that change, our parser is only about 1 to 1.5x slower than fastparse, which is way more reasonable. Will keep looking for other optimizations.
