### ISSUE TITLE
Bug with length restrictions on `rep`?

### ISSUE THREAD

**Issue by bblfish** [typelevel/cats-parse#199]
I am implementing [RFC 8941](https://www.rfc-editor.org/rfc/rfc8941.html#name-decimals) and noticed testing my code that length restrictions don't quite seem to work as I expected.

```scala
val signedDecIntegral: P[String] = 
   (P.char('-').?.with1 ~ digits.rep(1,12)).map { 
    case (min, i) =>
        min.map(_ => "-").getOrElse("")+i.toList.mkString
  }
val decFraction: P[String] = digits.rep(1,3).string
val sfDecimal: P[(String,String)] =
   (signedDecIntegral ~ (P.char('.') *> decFraction)).map { 
      case (dec: String,frac: String) =>
        (dec,frac.toList.mkString) //todo: keep the non-empty list?
     }
```       

It seems like the length restrictions don't cause the expected errors

```scala
scala> decFraction.parse("12312323")
val res17: Either[cats.parse.Parser.Error,(String, String)] = Right((,12312323))
scala> sfDecimal.parseAll("12345678901234567890.22222")
val res18: Either[cats.parse.Parser.Error,(String, String)] = Right((12345678901234567890,22222))
 ```

**Comment by bblfish** [comment]
Duh. My error. I was using `digits` which uses `rep`

**Comment by bblfish** [comment]
My implementation of [RFC 8941](https://github.com/co-operating-systems/Reactive-SoLiD/issues/13#issuecomment-817196664) using cats parse only took 2 days. 1.5 to code and .5 to test.

**Comment by johnynek** [comment]
Great to hear it worked out for you!
