### ISSUE TITLE
publish for Scala 3.0.0-RC3

### ISSUE THREAD

**Issue by hamnis** [typelevel/cats-parse#216]
needed for downstream http4s

**Comment by johnynek** [comment]
I'll try to get to this tonight.

**Comment by johnynek** [comment]
well, I tagged the release from the UI assuming that would work as well as pushing (I don't have my git credentials on this machine), and that didn't work...

I looked for a way to manually trigger the publishing action, but I can't see that....

I'll try to do it the old fashioned way tonight. Sorry for the delay.

**Comment by johnynek** [comment]
okay, the action is running: https://github.com/typelevel/cats-parse/actions/runs/818748614

**Comment by johnynek** [comment]
seems the publish worked.

Closing for now. Please reopen if there is a problem.
