### ISSUE TITLE
How to write recursive parsers?

### ISSUE THREAD

**Issue by glamm** [typelevel/cats-parse#228]
How do I write recursive parsers?  The following fails with a StackOverflowError.  I assume somewhere I don't have something tail-recursive, but I'm not sure how to write this any differently.  (Both `op` and `condexp` fail similarly below.)

```scala
package foo

import cats.parse.{Parser0, Parser, Numbers}
import cats.syntax.all._
import scala.language.postfixOps

sealed class Expr
case class Lit(x: Int) extends Expr
case class Op(left: Expr, op: String, right: Expr) extends Expr
case class Cond(cond: Expr, tr: Expr, fl: Expr) extends Expr

object testrecurse {
    import Parser._

    def expr: Parser[Expr] = recursive[Expr] { recurse =>
        def subexpr = recurse.between(char('('), char(')'))
        def lit = Numbers.digits.map(_.toInt).map(Lit(_))
//        def condexp = ((recurse <* char('?')) ~ recurse ~ (char(':') *> recurse))
//            .map { case ((cond, tr), fl) => Cond(cond, tr, fl) }           
        def op = (recurse, stringIn(List("+", "-", "*", "/")), recurse)
            .mapN(Op(_, _, _))

        oneOf(subexpr :: op :: lit :: Nil)
    }

    def main(args: Array[String]): Unit = {
        //val expr = "1?(5):2"
        val expr = "(5+3)/2"
        println(testrecurse.expr.parse(expr))
    }
}
```

**Comment by johnynek** [comment]
1. you don't need the `defer(recurse)` since `recurse` is already a value, the defer isn't doing anything.
2. op first has to parse `recurse` so that's your infinite loop.
3. I think your real question is how do you parse infix (or suffix operators).

A pattern I like is:
```scala
val nonOps: Parser[Expr] = subexp | lit
val operator: Parser[Expr => Expr] =
  (stringIn("+" :: "-" :: "*" :: "/" :: Nil), recurse).mapN { (op, right) => { expr: Expr => Op(expr, op, right) }

val result = Parser[Expr] = (nonOps ~ operator.rep0).map { case (init, ops) => ops.foldLeft(init) { (i, fn) => fn(i) }

result
```

So, you break the operator parsing apart. You have to be a bit more sophisticated if you want to get precedence correct.

**Comment by re-xyr** [comment]
What about having a `deref[A](x: Reference[Parser[A]]): Parser[A]` that derefs a parser in a `Reference` upon execution? If so we can first declare a list of `Reference`s and then reassign the contents of them (where we can freely cross reference).

**Comment by johnynek** [comment]
How is that different than `defer`?

The issue is that you still have to be careful to make some progress before doing recursion. Otherwise you set up an infinite loop.

**Comment by re-xyr** [comment]
Oh sorry - didn't read the API thoroughly. I think maybe we can explain how to deal with left recursion in README?

**Comment by glamm** [comment]
@johnynek Thanks for the response.  That did answer my question but revealed that I need to learn a lot more about the complexities of parsers.  I'll close this issue.
