### ISSUE TITLE
API to read source position

### ISSUE THREAD

**Issue by re-xyr** [typelevel/cats-parse#234]
As title. ANTLR allows to read the source interval (start offset, end offset, start row, end row, start col, end col) of any node. Trifecta has `DeltaParsing`. I did not find such an API here and I think this is a crucial feature for any further error reporting after parsing.

**Comment by johnynek** [comment]
There is Parser.index which gives the current offset, which can be used to get the range: get index, parse, get the index. If you want line and column numbers see LocationMap which can convert offsets into rows and columns.

**Comment by re-xyr** [comment]
I see. Do we want to provide `Caret`s and `Span`s like Trifecta? If so maybe I can make a pr.

**Comment by johnynek** [comment]
Yeah, that could be nice, especially if we can do it without breaking compatibility.
