### ISSUE TITLE
Replacing parsed text upon identification.

### ISSUE THREAD

**Issue by Ktedon** [typelevel/cats-parse#247]
I am trying to implement a string parser (with escape characters) and my goal is to replace the escaped characters as to get a perfect representation of what the user is trying to represent. My issue with have it skip over is that I don't know how to make it detect the end of a string. My current code is:
```scala
final case class StringLiteral(value: String)

private[this] val stringLexer       : P[StringLiteral] = {
    ((dquote ~ dquote) | (dquote ~ vchar.rep ~ dquote)).string
	.map(value => StringLiteral(value))
}
```
But this will only stop when it detects a non-printable character.

Can you replace a sequence of characters once it is recognized?

Any help would be greatly appreciated. Also, is there any documentation I'm missing?

**Comment by Ktedon** [comment]
I should clarify I mean parsing strings like: "weiuhf\nj\"\\\\"k"

**Comment by johnynek** [comment]
Sorry I missed this. I don't understand your question. You can make a parser of a `Char`, then map each `Char` then use repAs so make a String.

If you mean how do you deal with parsing escape sequences, here is an example:

https://github.com/typelevel/cats-parse/blob/f3f7686269fa2e23eaee1248db8b380c5fcbfa50/bench/src/main/scala/cats/parse/bench/self.scala#L130

it's a bit complex... we could possibly include a utility to parse some common encodings (java, json, python, etc...)

**Comment by Ktedon** [comment]
Yes, this is interesting but on the other hand it might be much easier for a programmer to just do some preprocessing on the file and parse that. It should be easier in this context (and faster) than encoding it in cats-parse.
