### ISSUE TITLE
Upgrade GitHub Actions

### ISSUE THREAD

**Issue by rossabaker** [typelevel/cats-parse#25]
Some of our GitHub Actions are a bit old, and we are getting [deprecation warnings](https://github.com/typelevel/cats-parse/actions/runs/344254889).  My hyopthesis is that at least one of our actions is making a deprecated call.

**Comment by djspiewak** [comment]
There's already an upstream release: https://github.com/djspiewak/sbt-github-actions/releases/tag/v0.9.4 It's still a GFI :-)

**Comment by zmccoy** [comment]
I can grab this update if y'all want.
