### ISSUE TITLE
Readme example does not parse 

### ISSUE THREAD

**Issue by DenisNovac** [typelevel/cats-parse#272]
Hi everyone. I tried to run `parserFile` from the example. To run an example i made own bench file (see #258).

Here is my code (i use circe for convenience):

```scala
val json      = """
{
  "some_flag": true,
  "some_number": 1,
  "some_thing": null
}
"""
val circeJson = circe.parser.parse(json).toOption.get
println(circeJson)  // it works since it is valid json

val r = parserFile.parse(circeJson.spaces2)
println(r) 
```

This code prints:

```
// string json println
{
  "some_flag" : true,
  "some_number" : 1,
  "some_thing" : null
}

// parser println (all whitespaces and line breaks saved):
Left(Error(0,NonEmptyList(InRange(0,	,
), InRange(0,
,
), InRange(0, , ))))
```

I have [this project](https://github.com/DenisNovac/cats-parse-test/blob/main/src/test/scala/ru/naumen/dyablochkin/learncatsparse/010JsonExample.scala) with runnable scalatest example of error.

**Comment by johnynek** [comment]
thanks for the report...

I do recall now that I noticed something that was left out, but I don't recall what it was now. :/

Here is a very similar code:
https://github.com/johnynek/bosatsu/blob/ebbcd537561b282d1c6e324b42bb9ad6928b707b/core/src/main/scala/org/bykn/bosatsu/Json.scala#L153

which is tested with scalacheck. That parser does work AFAIK. So, we just need to see what is wrong in this example.

**Comment by johnynek** [comment]
oh... I think I recall: there was a PR that changed the separator to use `surroundedBy` but it needs to use `.soft` to be correct.

In the example:
```scala
    val listSep: P[Unit] =
      P.char(',').surroundedBy(whitespaces0).void
```
in mine:
```scala
    val listSep: P[Unit] =
      (whitespaces0.with1.soft ~ P.char(',') ~ whitespaces0).void
```

Can you try making that change? And see if it works?

Another thing we should do is actually test the parser we are using as an example in the current repo, and also make sure the readme copies the tested version.

**Comment by zsluedem** [comment]
Same try and can not work here.

Even with your fix @johnynek .

**Comment by johnynek** [comment]
I have pretty solid tests for the parser in bosatsu:

https://github.com/johnynek/bosatsu/blob/master/core/src/test/scala/org/bykn/bosatsu/JsonTest.scala

There may be other differences, can you just copy the one there and try that?

**Comment by zsluedem** [comment]
@johnynek https://github.com/typelevel/cats-parse/pull/274 a fix.

I am also curious why the parse result would be [Either[Parser.Error, (String, A)]](https://github.com/typelevel/cats-parse/blob/main/core/shared/src/main/scala/cats/parse/Parser.scala#L64) and what is the `String` inside stands for.

**Comment by johnynek** [comment]
The String inside is the rest of the string that was not parsed. You can use parseAll if you want to require parsing everything.

**Comment by DenisNovac** [comment]
It works with the fix, thanks
