### ISSUE TITLE
What exactly `recursive` method does?

### ISSUE THREAD

**Issue by DenisNovac** [typelevel/cats-parse#275]
Hi everyone. In the [FastParse's docs](https://com-lihaoyi.github.io/fastparse/#Json) there is no `recursive` method or anything like this in JSON parsing example. It also says:

> The P(...) lets you write mutually recursive parsers, without running into circular initialization problems

So the parsers in FastParse are recursive by default and the parsers in cats-parse are not so you have to use `recursive`?

**Comment by johnynek** [comment]
see an example here:
https://github.com/typelevel/cats-parse/blob/0f9d8dcae0831fa50e752b17b5e4b8d42531ed31/bench/src/main/scala/cats/parse/bench/self.scala#L35

`recursive` is just a convenience to avoid having to manually form a loop. The benefit is you cannot inline such a loop, consider:

```scala
def recursive[A](fn: Parser[A] => Parser[A]): Parser[A] = {
  lazy val res = Parser.defer(fn(res))
  res
}

// Parser not(B | AB | AAB | ...)
Parser.not(Parser.recursive { rec =>
  Parser.string("B") | (Parser.string("A") ~ rec).string
})
```
Note, the above would be better written as `not(string("A").rep0.with1 ~ string("B"))`, but I just wanted to make an example.

Does that help at all? It is a convenience method, not fundamental, but it is useful to clearly declare some parsers as recursive (such as json, or xml, or whatever...).

If you prefer, you can use the style of:
```scala
lazy val myParser: Parser[Foo] = {
  // don't force evaluation of myParser
  val rec = Parser.defer(myParser)
  ...
}
```

**Comment by johnynek** [comment]
By the way, one thing we try in this codebase is to be in harmony with cats. Cats has the defer typeclass:

https://github.com/typelevel/cats/blob/main/core/src/main/scala/cats/Defer.scala

which is what enables recursive (which we call fix in Defer, but recursive may be a better name... which we used here in conflict to my above statement about harmonization).

**Comment by nikololiahim** [comment]
So, if I want to write a mutually-recursive parser, like:
```scala
val foo: P[String] = (
    ...
    bar
    ....
)

val bar: P[String] = (
    ...
    foo
    ...
)
```
Then, I would want to wrap both `foo` and `bar` in `P.defer`, like:
```scala
val foo: P[String] = P.defer(
    ...
    bar
    ....
)

val bar: P[String] = P.defer(
    ...
    foo
    ...
)
```
And that's it? Or do I also have to make `foo` and `bar` `lazy val`s?

**Comment by johnynek** [comment]
yeah, you would use `defer` there.

You can use `lazy` or `def` if there is some other reason, but there is nothing in the parsing library that would require it.

**Comment by DenisNovac** [comment]
Thanks everyone for answers. But i still can't really find a way to use it. Shouldn't those two parsers give the same output?
```scala
final case class LetterAndNumber(value: String) extends AnyVal

val parser = (alpha | digit).rep.string.map(r => LetterAndNumber.apply(r))

val parser2 = Parser
    .recursive { recurse =>
      (alpha ~ recurse) | (digit ~ recurse)
    }
    .string
    .map(x => LetterAndNumber(x))

println(parser.parse("AB1"))
// Right((,LetterAndNumber(AB1)))

println(parser2.parse("AB1"))
// Left(Error(3,NonEmptyList(InRange(3,0,9), InRange(3,A,Z), InRange(3,a,z))))
```

**Comment by DenisNovac** [comment]
Thanks everyone for answers, i guess now i get it.
