### ISSUE TITLE
Parser creation performance

### ISSUE THREAD

**Issue by DieMyst** [typelevel/cats-parse#279]
Our language parsing is based on cats-parse:
https://github.com/fluencelabs/aqua

It is quite complex and has more than 30 baseline expressions and their variances. `cats-parse` works fast but its initialization takes over 5 seconds. 

This creates a problem since now we are doing CLI which will compile commands in our language and execute them. That is, in fact, each call will take more than 5 seconds. I wonder if there are some ways to optimize the creation of the parser or serialize it so that the parser can be read from the disk?

**Comment by johnynek** [comment]
note that two optimizations may significantly help you:

1. #291 this could be a significant optimization when have a lot of `oneOf` or `orElse` in your code at creation time.
2. #280 this is a significant runtime performance improvement especially exposed with oneOf.

**Comment by DieMyst** [comment]
Thanks for the answers and solutions!
I changed all `def`s to values and it improve creation performance. But it worked better for java. Creation time decreased from ~5 seconds to ~1 seconds. But for JS build (our main usage) it only decreased from ~5 seconds to ~3-4 seconds. It is better than nothing and I'll be waiting for new releases with optimizations. 
thanks again!

**Comment by johnynek** [comment]
https://github.com/typelevel/cats-parse/releases/tag/v0.3.5

the latest release is out.

I'd love to hear what the numbers you report above look like with that version. Can you share?
