### ISSUE TITLE
Either x or not y

### ISSUE THREAD

**Issue by ohuu** [typelevel/cats-parse#316]
I have a few cases where I'm trying to parse something like this: 

```scala
eitherOr(P[SomeType], !string("{"))`
```

This won't work because the first parser is `P` and the second is `P0`. It seems like this kind of parser is sensible (although I'm happy to be corrected) and in fact this should be legal if only I could convert `P0` to `P`.

Is there a way of converting `P0` to `P` in this case or is there a way to restructure the parser or is this just a non-sensical parser to define.

I hope that makes sense.

**Comment by nikololiahim** [comment]
If I understand you correctly, you are trying to parse the first parser if it is not followed by '{'. 

I think, something like this would be more appropriate without the need to handle eithers, like `Left(())`:

```
P[SomeType].soft <* !string("{")
```

**Comment by johnynek** [comment]
People sometimes get confused about what not or `!` does. Some folks think it parses a single character if parser does not match. That's not what it does.

It parses nothing if the parser does not match, if the parser does match the parse fails.

By the way, if you wanted to parse any character that doesn't match something, that would be:

```scala
!P.string("something").with1 *> P.anyChar
```

So, in this case it would help us if you describe the parser you want since there has been so much confusion around the `not` method.

**Comment by ohuu** [comment]
@johnynek thanks for clearing that up.

I'm trying to implement a graphql engine and this appears in several places in the spec. For example [here](https://spec.graphql.org/October2021/#sec-Objects).

Basically there is an optional block of code delimited by `{` and `}` if the block is not present then no opening `{` is allowed.

**Comment by johnynek** [comment]
I would parse that as `blockParser.between(P.char('{') <* spaces, spaces.with1 *> P.char('}'))` or something like that.

so, if you hit `{` you must parse the block and the closing `}` or you fail (no backtracking on that).

**Comment by johnynek** [comment]
so, you could do
```scala
val block = name.repSep(sep = spaces1).between(P.char('{') <* spaces0, spaces0.with1 *> P.char('}'))
val selection = (name <* spaces0) ~ block.?
```
something like that.

Where `spaces0: Parser0[Unit]` which parses 0 or more whitespace and `spaces1: Parser[Unit]` which parser 1 or more.

**Comment by ohuu** [comment]
that's great thanks 👍
