### ISSUE TITLE
Rep same char as surrounded by

### ISSUE THREAD

**Issue by peter-jerry-ye** [typelevel/cats-parse#342]
Hello,

I'm trying to write a toml parser with cats-parse, and I come up with a problem when parsing multiline basic string.

The string requires triple quotation marks to mark the begin and the end, and quotation marks repeated once or twice is allowed inside. For example, a string of 7 quotation marks should be parsed to 1 quotation marks and a string of 8 quotation marks should be parsed to 2 quotation marks.

The version I came up with naively was (for clarity purpose, the quotation mark is changed to 'a'):
 ```scala
Parser.char('a').rep(1, 2).string.surroundedBy(Parser.string("aaa")).parseAll("aaaaaaa")
```
but it does not work.

I presume it's an arresting failure on the right, so I tried to add soft:
```scala
((Parser.string("aaa") *> Parser.char('a').rep(1, 2).string).soft <* Parser.string("aaa")).parseAll("aaaaaaa")
```
but it does not work either.

Could anyone give me a hint? Thank you.

**Comment by johnynek** [comment]
These parsers are greedy. So in your input you have 7 a characters to parse. You want 3 then 1 or 2 followed by 3 more.

The way this parser is written you surroundedBy is getting the first three, then it sees it can parse the maximum repetition (2) then it tries to parse the rest of the surroundedBy but finds only 2 left.

To do something like this I think you have to use backtracking:
```
string("aaa") *> (
  (char('a') *> string("aaa")).backtrack |
    (string("aa") *> string("aaa")
  )
```

I gather this is a toy example though. Probably you should adjust your approach if you can to avoid backtracking.

**Comment by peter-jerry-ye** [comment]
Thank you for your advise. I'll give it a try.

**Comment by peter-jerry-ye** [comment]
It seems that the first one using backtracking works well, but the second one would fail since `!tripleQuote` would fail when it sees the rest 4 characters.

I also looked at the example of fastparse, which is something like this:
`def TripleTail[_: P] = P( TQ ~ "\"".rep )`
So I might try it this way. 

Thanks for your help.

**Comment by johnynek** [comment]
Fastparse backtracks by default so copying parsers there please be aware of that.

**Comment by peter-jerry-ye** [comment]
Thank you for reminding.
