### ISSUE TITLE
Is it possible to support Scala Native?

### ISSUE THREAD

**Issue by i10416** [typelevel/cats-parse#371]
Is it possible to support Scala Native?

Fastparse supports scala native(2.12, 2.13) but does not support scala 3. On the other hand, catsparse supports scala 3, but does not support scala native😖

**Comment by i10416** [comment]
Thanks! I will try it!

**Comment by johnynek** [comment]
Exciting! Thanks!

**Comment by armanbilge** [comment]
FYI, if you are looking for the combination of Native+Scala3 you'll be blocked by https://github.com/typelevel/cats/issues/4117 which is blocked by https://github.com/typelevel/scalacheck/pull/868 which is presumably blocked by https://github.com/lampepfl/dotty/pull/14156 which comes in Scala 3.1.2.

**Comment by Erdemus** [comment]
It's actually a really nice option to write compilers using Scala Native.

**Comment by johnynek** [comment]
Closed by #376 and #426
