### ISSUE TITLE
design for scoping parsers for error reporting

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats-parse#43]
Currently, when a parser fails you get a nonempty list of offsets and failed expectations.

We could also add "scope" wrapper, like: `number.scope("number").orElse(str.scope("string"))`. How this would work is the mutable State would have a stack of these scopes, and we have:

```scala
case class ScopeParser[A](parser: Parser[A], scope: String) extends Parser[A]
```
in parseMut we would push the current scope onto the stack, then parse with parser, then pop it off the stack.

When we error, we take a snapshot of the current scope stack.

So, if we do this, users can have an easier time labeling parts of their parsers and seeing where things went wrong.

Fastparse does something similar.

What do you think of this design @mpilquist @non @rossabaker and really anyone who cares to comment.

**Comment by mpilquist** [comment]
:+1: At least superficially, this seems similar to the named codec support in scodec.

```scala
@ val c = int8.withContext("x") ~ (ignore(8) ~ constant(0).withContext("z")).withContext("y")
c: Codec[(Int, (Unit, Unit))] = (x(8-bit signed integer), y((ignore(8 bits), z(constant(BitVector(8 bits, 0x00))))))

@ c.decode(hex"000011".bits)
res2: Attempt[DecodeResult[(Int, (Unit, Unit))]] = Failure(General("expected constant BitVector(8 bits, 0x00) but got BitVector(8 bits, 0x11)", List("y", "z")))
```

**Comment by kubukoz** [comment]
Named parsers would be wonderful, especially if expectations also had access to the scope 😅
