### ISSUE TITLE
Add a way to make a fully generally parser

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats-parse#49]
users should be able to give us `(String, Int) => Either[Error, (Int, A)]` for cases where they can't express their parsing in terms of the core combinators.

Then we would at runtime check if the Int is `>=` the input offset, and it it is return, else report an InvariantViolationError or something for the parser (which I guess would be an epsilon error), or potentially throw an exception, since users should not be able to recover from errors like that...

An alternative is just let all bets be off, and not check that the returned Index makes sense, and just let users live with the consequences.

This is a can of worms, and maybe we should avoid adding such a function.

**Comment by elimirks** [comment]
Do you have examples of when this is necessary?

**Comment by johnynek** [comment]
Suppose you have another parser you'd like to embed inside a cats parse parser, that would be one example.

A second example is supporting something we could support but don't (e.g. getting access to the whole String).

I don't think it is a great idea, but it is an escape hatch if someone gets in an unusual place.

**Comment by morgen-peschke** [comment]
I've got a concrete example from something I'm working on at the moment.

Unless I'm missing a standard combinator, this is currently how to parse an integer:
```scala
final val integer: Parser[Int] =
  Parser
    .charIn('0' to '9')
    .rep
    .map { chars =>
      chars
        .foldLeft(new StringBuilder(chars.length))(_ append _)
        .mkString
    }
    .flatMap { input =>
      Either
        .catchNonFatal(input.toInt)
        .fold(
          _ => Parser.failWith(s"Invalid number: $input"),
          Parser.pure
        )
    }
```

**Comment by johnynek** [comment]
You might want to take a look at:

https://github.com/typelevel/cats-parse/blob/main/core/shared/src/main/scala/cats/parse/Numbers.scala

Also note the repAs method that can build the string in a more efficient manner than you do here.

Lastly, you can parse a signed int32 without parsing the string and maybe failing, but it is more work: you either parse a - or not. If you don't see a - you either see 0, or 1 followed by 0 to 8 digits, etc...

This is like building a regular expression for a limited integer. It's probably worth implementing and adding to Numbers so people don't have to struggle with it.

That said, I do question if a parse error is what you want here vs an error message that says the number is too large. That can be done by using Numbers + filter (or flatMap but filter can be more efficient).

**Comment by elimirks** [comment]
I do this for unsigned ints:

```scala
  def safeToInt(value: String): Option[Int] =
    Try(value.toInt).toOption

  val uintP: Parser[Int] = Numbers.digits.mapFilter(safeToInt)
````

**Comment by morgen-peschke** [comment]
Thanks for pointing me towards `Numbers`. Aside from the direct stuff, it's got a lot of good examples.

In my case, a parse error is desirable because I'm using it to parse command line arguments, so an out of bounds number is going to be less common than a parse error caused by an extraneous quote.
