### ISSUE TITLE
Link errors when crossbuilding for scalaJS or scalaNative

### ISSUE THREAD

**Issue by erikerlandson** [typelevel/cats-parse#526]
I've been using cats-parse here:
https://github.com/erikerlandson/coulomb/pull/420

And I am getting link errors when I try to build my tests for either scalaJS or scalaNative. Is there support for those platforms?  This is a Scala-3 build.

**Comment by erikerlandson** [comment]
cc @armanbilge  @benhutchison

**Comment by armanbilge** [comment]
https://youforgotapercentagesignoracolon.com/

**Comment by erikerlandson** [comment]
this was operator error, forgot to use `%%%`
