### ISSUE TITLE
investigate mima failure on dotty

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats-parse#59]
https://github.com/typelevel/cats-parse/runs/1392179131?check_suite_focus=true

looks like the dotty version of 0.1.0 didn't publish... maybe I have to rerun some ci job....

ugh

**Comment by johnynek** [comment]
cc @mpilquist if you have any spare time.

**Comment by johnynek** [comment]
It seems release worked:

https://github.com/typelevel/cats-parse/runs/1388807347?check_suite_focus=true

but now the CI is indeed broken:

https://github.com/typelevel/cats-parse/runs/1398137196?check_suite_focus=true

It seems we published with RC-1, but the mima is downloading RC-1

**Comment by johnynek** [comment]
Is this some bug with how the URLs are formed?

**Comment by mpilquist** [comment]
Yeah, the suffix for 0.27.0-RC1 JAR is `_0.27` but mima config is incorrectly using the `_0.27.0-RC1` suffix. This doesn't occur with 3.0.0-RC1, where the JAR suffix is `_3.0.0-RC1`. Simplest fix is probably just removing 0.27.0-RC1 support.

**Comment by johnynek** [comment]
Thanks for fixing this @mpilquist 

see #63
