### ISSUE TITLE
Please release 1.1.0 with Scala Native 0.5 support

### ISSUE THREAD

**Issue by antonsviridov-src** [typelevel/cats-parse#628]
Howdy 👋 

Seems like PRs bumping Scala Native have long been merged, but there's so far no new release.

Could you please release 1.1.0? If there is work necessary to do that, I volunteer myself or @keynmol.

Cats itself bumped to SN0.5 in a minor release so there is precedent in TL org. 

![CleanShot 2024-12-11 at 12 07 10](https://github.com/user-attachments/assets/7a8ad156-5123-47ea-96d3-f96d237b309c)

**Comment by valencik** [comment]
Just +1 that this should be a minor version bump, not a patch release.

That will give us at least some wiggle room if we *needed* a new release for libraries unable to update to Scala Native 0.5, like http4s.

**Comment by johnynek** [comment]
I am beginning this process now.

**Comment by johnynek** [comment]
https://github.com/typelevel/cats-parse/releases/tag/v1.1.0

I *think* this release is going out now: https://github.com/typelevel/cats-parse/actions/runs/12281768543
