### ISSUE TITLE
Failing test cases in main

### ISSUE THREAD

**Issue by non** [typelevel/cats-parse#72]
I'm seeing two tests failing:

 - `cats.parse.ParserTest.voided only changes the result`
 - `cats.parse.ParserTest.with1 *> and with1 <* work as expected`

The errors have the form:

```
values are not the same
=> Diff (- obtained, + expected)
           upper = 'ﷷ'
+        ),
+        Fail(
+          offset = 0
         )
```

To reproduce add the following to `ParserTest`:

```scala
override val scalaCheckInitialSeed = "SDzb3fKPxR67aeO2sgq4BlvTm5NphF9OM4j-dSIS9RD="
```

I haven't dug into this -- just figured I should report it ASAP.

**Comment by non** [comment]
(Pleasantly surprised how easy munit makes it to add this failing seed too!)

**Comment by johnynek** [comment]
I think this is due to some new optimizations that have removed a trailing Fail error (which is a bit silly, but is added by oneOfs if nothing matches, which is probably shouldn't)
