### ISSUE TITLE
rep with min and max

### ISSUE THREAD

**Issue by rossabaker** [typelevel/cats-parse#97]
Related to #52, question was raised about parsers that repeat a min and a max number of times.  Here's a real-world case from RFC7321, which has a precision to the thousandths:

```
     qvalue = ( "0" [ "." 0*3DIGIT ] )
            / ( "1" [ "." 0*3("0") ] )
```

It's not real common, but they're out there.

**Comment by johnynek** [comment]
Applicative replicateA will do it a fixed number of times, that with unions should work. That said we can pretty easily support it directly and be a bit more efficient.

**Comment by regadas** [comment]
Interesting, there's a case for it after all! We can resurrect some of that work.
